clegaspi/saml_reader

README.md
saml_reader/cert.py
saml_reader/cli.py
saml_reader/har.py
saml_reader/saml.py

Finally paid my technical debt. Added a bunch of todos as well for improvements that can be made.

Add documentation and update Readme

---

README.md
saml_reader/cli.py
saml_reader/mongo.py
saml_reader/parser.py
saml_reader/saml.py
saml_reader/text_reader.py

I added a bunch of MongoDB-specific tests and validation based on input values.
I also rearranged the code to make it more modular.

Abstract and expand MongoDB tests

---

saml_reader/saml/parser.py
saml_reader/validation/mongo.py

Fixing issues filed as bugs and set for 0.0.3.
#17 #18 #20

Fixing filed bugs

---

saml_reader/cli.py

Refactor user input

---

saml_reader/saml/errors.py
saml_reader/saml/oli.py
saml_reader/saml/parser.py
saml_reader/text_reader.py
setup.py

Refactor OneLogin integration

---

.travis.yml
README.md
tests/test_test.py

Let's see if we can get this to work

Add TravisCI for autotesting

---

saml_reader/saml/parser.py

Forgot I want to merge this to the v_0_0_4 branch. Been too long.

Revert "issue #33 - add logic to strip whitespace from base64 string"

---

saml_reader/saml/parser.py

Forgot I want to merge this to the v_0_0_4 branch. Been too long.

Adding PR#44 to feature branch

---

saml_reader/cli.py

I made an oversight when merging in #48 which would have been caught by tests...guess I better get on that

Fix Issue #54

---

saml_reader/cli.py
saml_reader/saml/base.py
saml_reader/saml/oli.py
saml_reader/saml/parser.py
saml_reader/validation/mongo.py

Handle duplicate attributes in SAML response

---

saml_reader/cli.py

Handle FileNotFoundError for input files

---

saml_reader/saml/parser.py

Read ACS URL from alternate location

---

saml_reader/saml/parser.py

Fix #35. Regex doesn't need changing because the current regex can find it in either location.

Read cert from main body in standard parser

---

saml_reader/cli.py
saml_reader/validation/mongo.py

Remove email attribute tests, and refactor some information based on this (lack of) requirement. Fixes #42

Remove required email attribute

---

saml_reader/cli.py

If stdin is not a file redirect or pipe, gives nice error. Fixes #51

Checks for empty stdin

---

saml_reader/web/app.py
saml_reader/web/layouts/analyze.py

Addresses #59. If we need more, will do so later.

Add more docs to webpage

---

.gitignore
setup.py

Fix dash-extensions version

---

.gitignore
README.md
setup.py

- See https://github.com/clegaspi/saml_reader/issues/85 for writeup.

Patch Werkzeug breaking change

---

saml_reader/cert.py
saml_reader/validation/input_validation.py
setup.py

Python 3.11 support

---

README.md
saml_reader/saml/oli.py
setup.py

Compatibility issues addressed

---

saml_reader/saml/oli.py
saml_reader/saml/parser.py

Address #96 and clean up how SAML data is parsed. Get rid of lambdas.

#96: check for valid acs

---

saml_reader/saml/oli.py
saml_reader/validation/mongo.py

Fix #80 and also fix issue with #96 that I introduced (oops)

Issue #80: Check for multivalued attributes
